# RX Server Configuration Example

[server]
# Maximum number of client connections
max_clients = 256

# TCP port base (actual port = tcp_port_base + display_number)
tcp_port_base = 6000

# Enable TCP connections (usually disabled for security)
enable_tcp = false

# Unix socket path template ({display} will be replaced with display number)
unix_socket_path = "/tmp/.X11-unix/X{display}"

# Display number for the server (default is 0)
display_number = 1

[display]
# Screen resolution
width = 1920
height = 1080

# Color depth (bits per pixel)
depth = 24

# Display DPI
dpi = 96

[graphics]
# Enable hardware acceleration if available
hardware_acceleration = true

# Graphics backend ("software" or "hardware")
backend = "software"

# Maximum texture size
max_texture_size = 4096

[input]
# Keyboard repeat delay in milliseconds
keyboard_repeat_delay = 500

# Keyboard repeat rate in Hz
keyboard_repeat_rate = 30

# Mouse acceleration factor
mouse_acceleration = 1.0

[logging]
# Log level: "error", "warn", "info", "debug", "trace"
level = "info"

# Log file path (optional, leave empty to disable file logging)
# file = "/var/log/rxserver.log"

# Log to stdout
stdout = true
