[logging]
default_level = "trace"
show_thread_ids = false
show_thread_names = true
ansi = true
show_file_location = false
file = "rxserver.log"
console = true

[[transports]]
kind = "tcp"
bind_address = "0.0.0.0:6000"

[[displays]]
id = 0
kind = "virtual"
name = "Primary Monitor"
resolution = [1920, 1080]
debug_overlay = false
