[network]
listen_address = "127.0.0.1"
port_base = 6000
tcp_keepalive = false
connection_timeout = 30

[logging]
level = "info"
colored = true
json = false

[plugins]
enabled = true
search_paths = []
disabled = []

[security]
access_control = true
allowed_hosts = []
max_auth_attempts = 3

[performance]
max_connections = 100
buffer_size = 8192
request_batching = true
