[logging]
default_level = "trace"
show_thread_ids = false
show_thread_names = true
ansi = true
show_file_location = false
file = "rxserver.log"
console = true

[[displays]]
id = 0
kind = "virtual"
name = "Primary Monitor"
transport = "tcp"
resolution = [1920, 1080]

# [[displays]]
# id = 1
# type = "virtual"
# name = "Secondary Monitor"
# transport = "tcp"
# resolution = [2560, 1440]
