# RX Server Configuration Example
# This file demonstrates all available configuration options with their default values.

[server]
# Maximum number of concurrent client connections
max_clients = 256
# X11 display number (e.g., 0 for :0)
display_number = 0
# Base TCP port (actual port = tcp_port_base + display_number)
tcp_port_base = 6000
# Enable TCP connections (Unix sockets are always enabled)
enable_tcp = false
# Unix socket path template with {display} placeholder
unix_socket_path = "/tmp/.X11-unix/X{display}"

[transport]
# Maximum buffer size for transport operations (bytes)
max_buffer_size = 65536
# Connection timeout (seconds)
connection_timeout = 30
# Enable compression for data transport
enable_compression = false

[network]
# Enable IPv6 support
enable_ipv6 = false
# List of allowed IP addresses (empty = allow all)
allowed_ips = []
# Enable access control mechanisms
enable_access_control = false

[display]
# Screen dimensions in pixels
width = 1920
height = 1080
# Color depth in bits per pixel (8, 16, 24, or 32)
depth = 24
# DPI for font rendering
dpi = 96
# Refresh rate in Hz
refresh_rate = 60

[graphics]
# Enable hardware acceleration if available
hardware_acceleration = true
# Graphics backend: "software", "opengl", or "vulkan"
backend = "software"
# Maximum texture size for hardware acceleration
max_texture_size = 4096
# Enable vertical synchronization
enable_vsync = false

[input]
# Keyboard repeat delay in milliseconds
keyboard_repeat_delay = 500
# Keyboard repeat rate in Hz
keyboard_repeat_rate = 30
# Mouse acceleration factor
mouse_acceleration = 1.0
# Mouse sensitivity multiplier
mouse_sensitivity = 1.0

[logging]
# Log level: "error", "warn", "info", "debug", or "trace"
level = "info"
# Optional log file path (comment out to disable file logging)
# file = "/var/log/rxserver.log"
# Whether to log to stdout/stderr
stdout = true
# Maximum log file size in MB before rotation
max_file_size = 100
# Number of rotated log files to keep
rotation_count = 5
